baseurl = "avillarreal.io"
title = "Alan Villarreal"
copyright = "Copyright &copy; 2020 - Alan Villarreal"
canonifyurls = true
theme = "hugo-kiera"
builddrafts = true

paginate = 3

#summaryLength = 50
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Alan Villarreal"
    linkedin = "avreal31"
    github = "avreal"
   # twitter = "ds_says"

[params]
    tagline = "Writing on Various Network Engineering and Network Programmability Topics"
    description = "Writing on Various Network Engineering and Network Programmability Topics"
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = ["styles-light.css"]  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "https://github.com/MyRepo"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10

 #uncomment to enable the Tags link on the main toolbar

# [[menu.main]]
#    identifier = "about"
#    name = "about"
#    url = "/about/about"
#    weight = 1


